import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Header } from '@/components/Header'

const satosho = localFont({
  src: './fonts/satoshi.woff2',
  variable: '--font-satoshi',
})

const intergralCF = localFont({
  src: './fonts/integralCF-Bold.woff2',
  weight: '700',
  variable: '--font-integral-cf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${satosho.className} ${intergralCF.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
