import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Header } from '@/components/Header'
import { MenuListProvider } from '@/contexts/MenuListContext'
import {
  SearchBarContext,
  SearchBarProvider,
} from '@/contexts/SearchBarContext'

const satosho = localFont({
  src: './fonts/satoshi.woff2',
  variable: '--font-satoshi',
})

const intergralCF = localFont({
  src: './fonts/integralCF-Bold.woff2',
  weight: '700',
  variable: '--font-integral-cf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${satosho.className} ${intergralCF.variable} bg-white antialiased overflow-x-hidden`}
      >
        <MenuListProvider>
          <SearchBarProvider>
            <Header />
          </SearchBarProvider>
        </MenuListProvider>
        {children}
      </body>
    </html>
  )
}
